apiVersion: v1
kind: Pod
metadata:
  name: multi-pvc-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data/config"
          name: config-volume
        - mountPath: "/data/logs"
          name: logs-volume
  volumes:
    - name: config-volume
      persistentVolumeClaim:
        claimName: pvc-config
    - name: logs-volume
      persistentVolumeClaim:
        claimName: pvc-logs